# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "calabash-cucumber", "~> 0.21.8"
gem "fastlane", "~> 2.119"
